services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orders:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
      - ${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}
      - ${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      WEB_SERVER_PORT: ${WEB_SERVER_PORT}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
      GRAPHQL_SERVER_PORT: ${GRAPHQL_SERVER_PORT}
    depends_on:
      - mysql
      - rabbitmq
    




