receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: jaeger-all-in-one:16686
    tls:
      insecure: true

  debug:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
